<a href="https://colab.research.google.com/github/muhajirakbarhsb/NLP_class_2023/blob/main/transformer_embeddings.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#!pip install transformers

Defaulting to user installation because normal site-packages is not writeable
     ---------------------------------------- 0.0/123.1 kB ? eta -:--:--
     --------- ----------------------------- 30.7/123.1 kB 1.4 MB/s eta 0:00:01
     ----------------------------- --------- 92.2/123.1 kB 1.1 MB/s eta 0:00:01
     -----------------------------------  122.9/123.1 kB 901.1 kB/s eta 0:00:01
     ------------------------------------ 123.1/123.1 kB 805.9 kB/s eta 0:00:00
   ---------------------------------------- 0.0/7.9 MB ? eta -:--:--
   ---------------------------------------- 0.1/7.9 MB 1.7 MB/s eta 0:00:05
    --------------------------------------- 0.1/7.9 MB 1.1 MB/s eta 0:00:07
   - -------------------------------------- 0.2/7.9 MB 1.6 MB/s eta 0:00:05
   - -------------------------------------- 0.3/7.9 MB 1.7 MB/s eta 0:00:05
   - -------------------------------------- 0.4/7.9 MB 1.7 MB/s eta 0:00:05
   -- ------------------------------------- 0.4/7.9 MB 1.6 MB/s eta 0:00:05
   -

DEPRECATION: Loading egg at c:\program files\python311\lib\site-packages\vboxapi-1.0-py3.11.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: celery 5.0.5 has a non-standard dependency specifier pytz>dev. pip 24.0 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of celery or contact the author to suggest that they release a version with a conforming dependency specifiers. Discussion can be found at https://github.com/pypa/pip/issues/12063


In [3]:
#!pip install torch

Defaulting to user installation because normal site-packages is not writeable
     ---------------------------------------- 0.0/5.7 MB ? eta -:--:--
     ---------------------------------------- 0.0/5.7 MB ? eta -:--:--
     ---------------------------------------- 0.0/5.7 MB ? eta -:--:--
     ---------------------------------------- 0.0/5.7 MB ? eta -:--:--
     ---------------------------------------- 0.0/5.7 MB ? eta -:--:--
     ---------------------------------------- 0.0/5.7 MB ? eta -:--:--
     ---------------------------------------- 0.0/5.7 MB 186.2 kB/s eta 0:00:31
     ---------------------------------------- 0.0/5.7 MB 163.4 kB/s eta 0:00:35
     ---------------------------------------- 0.0/5.7 MB 163.4 kB/s eta 0:00:35
      --------------------------------------- 0.1/5.7 MB 254.2 kB/s eta 0:00:23
      --------------------------------------- 0.1/5.7 MB 387.0 kB/s eta 0:00:15
      --------------------------------------- 0.1/5.7 MB 387.0 kB/s eta 0:00:15
     - ---------

DEPRECATION: Loading egg at c:\program files\python311\lib\site-packages\vboxapi-1.0-py3.11.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: celery 5.0.5 has a non-standard dependency specifier pytz>dev. pip 24.0 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of celery or contact the author to suggest that they release a version with a conforming dependency specifiers. Discussion can be found at https://github.com/pypa/pip/issues/12063


In [1]:
from transformers import AutoTokenizer, AutoModelForSequenceClassification
import torch

In [3]:
model_name = "distilbert-base-uncased-finetuned-sst-2-english"

In [4]:
tokenizer = AutoTokenizer.from_pretrained(model_name)

In [5]:
model = AutoModelForSequenceClassification.from_pretrained(model_name)

C:\Users\Alharidt\AppData\Roaming\Python\Python311\site-packages\huggingface_hub\file_download.py:137: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\Alharidt\.cache\huggingface\hub. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to see activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)


In [6]:

### 1. Tokenization
# Tokenizer documentation: https://huggingface.co/transformers/main_classes/tokenizer.html

text = 'I believe that the EU is trustworthy.'
print(f"Input text: '{text}'\n")

Input text: 'I believe that the EU is trustworthy.'



In [7]:

input_ids = tokenizer(text, truncation=True, return_tensors="pt")["input_ids"]
print(f"""The tokenizer splits the text string into separate tokens. A token is either an entire word,
or a 'sub-word unit' in case of rare words (or punctuation).
The word 'trustworthy', for example is split into two tokens: {tokenizer.tokenize("Trustworthy")}.
The main advantage of these sub-word units is that rare words cannot be out-of-vocabulary (an issue of other text-as-data approaches).
Transformer models typically have a vocabulary of around 30.000 - 250.000 tokens, learned from the training data.
Here is e.g. the vocabulary of DistilBERT: https://huggingface.co/distilbert-base-uncased/resolve/main/vocab.txt\n""")

The tokenizer splits the text string into separate tokens. A token is either an entire word,
or a 'sub-word unit' in case of rare words (or punctuation).
The word 'trustworthy', for example is split into two tokens: ['trust', '##worthy'].
The main advantage of these sub-word units is that rare words cannot be out-of-vocabulary (an issue of other text-as-data approaches).
Transformer models typically have a vocabulary of around 30.000 - 250.000 tokens, learned from the training data.
Here is e.g. the vocabulary of DistilBERT: https://huggingface.co/distilbert-base-uncased/resolve/main/vocab.txt



In [8]:
input_ids[0].tolist()

[101, 1045, 2903, 2008, 1996, 7327, 2003, 3404, 13966, 1012, 102]

In [9]:
tokenizer(text, truncation=True, return_tensors="pt")

{'input_ids': tensor([[  101,  1045,  2903,  2008,  1996,  7327,  2003,  3404, 13966,  1012,
           102]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])}

In [10]:
tokenizer.tokenize(text)

['i', 'believe', 'that', 'the', 'eu', 'is', 'trust', '##worthy', '.']

In [11]:
print(f"The input text is split into the following tokens:\n{tokenizer.tokenize(text)}.")
print("The tokenizer then maps each token to the corresponding token ID in the model's vocabulary:")
print(input_ids[0].tolist()[1:-1])
print("Transformer models only understand these token IDs.\n")

The input text is split into the following tokens:
['i', 'believe', 'that', 'the', 'eu', 'is', 'trust', '##worthy', '.'].
The tokenizer then maps each token to the corresponding token ID in the model's vocabulary:
[1045, 2903, 2008, 1996, 7327, 2003, 3404, 13966, 1012]
Transformer models only understand these token IDs.



In [12]:
print("""In addition, the tokenizer adds two special tokens:
 First, the [CLS] (classification) token is always added at the beginning.
        While individual tokens represent individual (sub)words, the [CLS] token represents the entire text.
        The [CLS] token "is  used  as  the  aggregate sequence representation for classification tasks" (Devlin et al. 2019: 4). Details: https://arxiv.org/pdf/1810.04805.pdf
 Second, the [SEP] token separates two texts. It is useful for tasks which require two text inputs, for example Questions & Answer tasks.
        (It is not relevant in our case)
\n""")

In addition, the tokenizer adds two special tokens:
 First, the [CLS] (classification) token is always added at the beginning.
        While individual tokens represent individual (sub)words, the [CLS] token represents the entire text.
        The [CLS] token "is  used  as  the  aggregate sequence representation for classification tasks" (Devlin et al. 2019: 4). Details: https://arxiv.org/pdf/1810.04805.pdf
 Second, the [SEP] token separates two texts. It is useful for tasks which require two text inputs, for example Questions & Answer tasks.
        (It is not relevant in our case)




In [13]:
print("""The final input for a BERT transformer model therefore looks like this:""")
token_strings = tokenizer.convert_ids_to_tokens(ids=input_ids[0])
#token_strings = tokenizer.tokenize(text)
for token_id, token_string in zip(input_ids[0].tolist(), token_strings):
  print(token_id, " == ", token_string)


# entire vocabulary: tokenizer.pretrained_vocab_files_map["vocab_file"]["distilbert-base-uncased"]
# https://huggingface.co/distilbert-base-uncased/resolve/main/vocab.txt

The final input for a BERT transformer model therefore looks like this:
101  ==  [CLS]
1045  ==  i
2903  ==  believe
2008  ==  that
1996  ==  the
7327  ==  eu
2003  ==  is
3404  ==  trust
13966  ==  ##worthy
1012  ==  .
102  ==  [SEP]


In [14]:
input_ids[0]

tensor([  101,  1045,  2903,  2008,  1996,  7327,  2003,  3404, 13966,  1012,
          102])

In [15]:
token_strings = tokenizer.convert_ids_to_tokens(ids=input_ids[0])
token_strings

['[CLS]',
 'i',
 'believe',
 'that',
 'the',
 'eu',
 'is',
 'trust',
 '##worthy',
 '.',
 '[SEP]']

In [16]:
for a,b in zip(input_ids[0].tolist(), token_strings):
    print(a,b)

101 [CLS]
1045 i
2903 believe
2008 that
1996 the
7327 eu
2003 is
3404 trust
13966 ##worthy
1012 .
102 [SEP]


In [17]:
text1 = "I learn python programming"
text2 = "the elephant is bitten by python snake"
#text1 = "I cook dinner everyday"
#text2 = "Mr cook went to sydney"
text3 = "I study python programming"
inp1 = tokenizer(text1, truncation=True, return_tensors="pt")["input_ids"]
inp2 = tokenizer(text2, truncation=True, return_tensors="pt")["input_ids"]
inp3 = tokenizer(text3, truncation=True, return_tensors="pt")["input_ids"]

In [18]:
tokenizer.tokenize(text1)

['i', 'learn', 'python', 'programming']

In [19]:
inp1

tensor([[  101,  1045,  4553, 18750,  4730,   102]])

In [20]:
inp2

tensor([[  101,  1996, 10777,  2003, 19026,  2011, 18750,  7488,   102]])

In [21]:
inp3

tensor([[  101,  1045,  2817, 18750,  4730,   102]])

In [22]:
model

DistilBertForSequenceClassification(
  (distilbert): DistilBertModel(
    (embeddings): Embeddings(
      (word_embeddings): Embedding(30522, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (transformer): Transformer(
      (layer): ModuleList(
        (0-5): 6 x TransformerBlock(
          (attention): MultiHeadSelfAttention(
            (dropout): Dropout(p=0.1, inplace=False)
            (q_lin): Linear(in_features=768, out_features=768, bias=True)
            (k_lin): Linear(in_features=768, out_features=768, bias=True)
            (v_lin): Linear(in_features=768, out_features=768, bias=True)
            (out_lin): Linear(in_features=768, out_features=768, bias=True)
          )
          (sa_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
          (ffn): FFN(
            (dropout): Dropout(p=0.1, inplace=False)
 

In [23]:
model.distilbert.transformer.layer[0].attention

MultiHeadSelfAttention(
  (dropout): Dropout(p=0.1, inplace=False)
  (q_lin): Linear(in_features=768, out_features=768, bias=True)
  (k_lin): Linear(in_features=768, out_features=768, bias=True)
  (v_lin): Linear(in_features=768, out_features=768, bias=True)
  (out_lin): Linear(in_features=768, out_features=768, bias=True)
)

In [24]:
e1 = model.distilbert.embeddings(inp1)
e2 = model.distilbert.embeddings(inp2)
e3 = model.distilbert.embeddings(inp3)

In [25]:
e1[0,3][:20]

tensor([ 0.4765,  0.0791, -0.5994,  0.1990, -1.1323,  1.2059, -0.6152,  0.1050,
        -0.6633,  0.7164,  0.8947,  0.2140, -0.9706, -0.0527, -0.5499, -1.1334,
         0.3393,  0.1940, -0.4095, -0.6861], grad_fn=<SliceBackward0>)

In [26]:
e2[0,6][:20]

tensor([ 0.6138, -0.0411, -0.5975,  0.3634, -1.0803,  1.2622, -0.8302,  0.3590,
        -0.6277,  0.6380,  0.3281,  0.4025, -1.0925,  0.0264, -0.8139, -1.0278,
         0.8216,  0.2391, -0.3296, -0.6926], grad_fn=<SliceBackward0>)

In [27]:
out1 = model(inp1, output_hidden_states=True, output_attentions=False, return_dict=True)
out2 = model(inp2, output_hidden_states=True, output_attentions=False, return_dict=True)
out3 = model(inp3, output_hidden_states=True, output_attentions=False, return_dict=True)

In [28]:
layer = 6
cosi = torch.nn.CosineSimilarity(dim=0)
output = cosi(out1.hidden_states[layer][0][3], out2.hidden_states[layer][0][6])
output

tensor(0.4203, grad_fn=<SumBackward1>)

In [29]:
we1 = model.distilbert.embeddings.word_embeddings(inp1)
we2 = model.distilbert.embeddings.word_embeddings(inp2)
we3 = model.distilbert.embeddings.word_embeddings(inp3)

In [30]:
#embedding layer = 0
cosi = torch.nn.CosineSimilarity(dim=0)
output = cosi(e1[0][2], e2[0][2])
output

tensor(0.0313, grad_fn=<SumBackward1>)

In [31]:
t1 = "I like python programming"
tt1 = tokenizer(t1, return_tensors='pt')['input_ids']

In [32]:
tt1

tensor([[  101,  1045,  2066, 18750,  4730,   102]])

In [33]:
t2 = "python bites cats"
tt1 = tokenizer(t1, return_tensors='pt')['input_ids']

In [34]:
model

DistilBertForSequenceClassification(
  (distilbert): DistilBertModel(
    (embeddings): Embeddings(
      (word_embeddings): Embedding(30522, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (transformer): Transformer(
      (layer): ModuleList(
        (0-5): 6 x TransformerBlock(
          (attention): MultiHeadSelfAttention(
            (dropout): Dropout(p=0.1, inplace=False)
            (q_lin): Linear(in_features=768, out_features=768, bias=True)
            (k_lin): Linear(in_features=768, out_features=768, bias=True)
            (v_lin): Linear(in_features=768, out_features=768, bias=True)
            (out_lin): Linear(in_features=768, out_features=768, bias=True)
          )
          (sa_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
          (ffn): FFN(
            (dropout): Dropout(p=0.1, inplace=False)
 

In [35]:
model.distilbert.embeddings

Embeddings(
  (word_embeddings): Embedding(30522, 768, padding_idx=0)
  (position_embeddings): Embedding(512, 768)
  (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
  (dropout): Dropout(p=0.1, inplace=False)
)

In [36]:
text1 = "I cook dinner everyday"
text2 = "Mr cook went to sydney"
#text1 = "I learn python programming"
#text2 = "the elephant is bitten by python snake"

inp1 = tokenizer(text1, truncation=True, return_tensors="pt")["input_ids"]
inp2 = tokenizer(text2, truncation=True, return_tensors="pt")["input_ids"]


In [37]:
inp1

tensor([[  101,  1045,  5660,  4596, 10126,   102]])

In [38]:
inp2

tensor([[ 101, 2720, 5660, 2253, 2000, 3994,  102]])

In [39]:
m1 = model(inp1, output_hidden_states=True, return_dict=True)
m2 = model(inp2, output_hidden_states=True, return_dict=True)

In [40]:
m1.hidden_states[0][0][2][:20]

tensor([-7.9770e-04, -1.3976e-01, -1.4937e-01, -3.5096e-01,  7.5117e-01,
        -7.1433e-01,  8.2337e-01, -7.5590e-01,  3.0664e-01, -1.1051e+00,
         4.1999e-01, -2.4543e-01,  3.9497e-01, -7.2123e-01,  5.4743e-01,
        -4.5326e-01,  5.1976e-02,  4.8805e-01, -1.1667e+00, -1.4705e-01],
       grad_fn=<SliceBackward0>)

In [41]:
m2.hidden_states[0][0][2][:20]

tensor([-7.9770e-04, -1.3976e-01, -1.4937e-01, -3.5096e-01,  7.5117e-01,
        -7.1433e-01,  8.2337e-01, -7.5590e-01,  3.0664e-01, -1.1051e+00,
         4.1999e-01, -2.4543e-01,  3.9497e-01, -7.2123e-01,  5.4743e-01,
        -4.5326e-01,  5.1976e-02,  4.8805e-01, -1.1667e+00, -1.4705e-01],
       grad_fn=<SliceBackward0>)

In [42]:
m1.hidden_states[layer][0][2]

tensor([ 6.0149e-01,  2.2652e-01,  5.9097e-01, -5.5999e-02,  1.0089e+00,
        -3.5355e-01, -5.3618e-01,  5.1649e-02, -8.7698e-01, -4.5678e-01,
        -1.8067e-01,  1.2356e-01,  4.1548e-01, -5.3361e-01,  2.0823e-01,
         3.7847e-01,  1.4650e+00,  8.3367e-01, -6.4652e-01, -1.0254e+00,
        -2.1726e-01, -9.1473e-01, -4.7155e-01,  1.1968e+00, -5.5341e-01,
        -5.5152e-03, -4.8573e-01,  1.8069e-01,  6.7272e-02, -1.9444e-01,
         1.2750e-01, -5.9318e-02, -3.6118e-01,  1.8814e-01, -2.0095e-01,
        -3.0335e-01, -1.2688e-01,  3.6854e-02, -1.0148e+00, -2.8779e-02,
         8.5624e-01, -2.9326e-02,  1.7209e+00, -4.9425e-01, -6.1353e-01,
        -1.0969e+00,  5.6158e-01,  5.4749e-01,  2.8105e-02, -1.8008e-01,
        -2.0972e-01,  3.4277e-01, -4.0938e-01,  1.1580e-02,  3.0186e-01,
         1.3056e+00, -9.6719e-01,  6.7040e-01, -8.7003e-01, -1.3564e+00,
        -8.1181e-01,  1.5536e-01,  5.4807e-01, -3.7488e-01,  7.3475e-01,
         6.4350e-01,  4.3223e-01,  1.0148e-02,  1.1

In [43]:
layer=1
output = cosi(m1.hidden_states[layer][0][2], m2.hidden_states[layer][0][2])
output

tensor(0.8369, grad_fn=<SumBackward1>)

In [44]:
layer=6
output = cosi(m1.hidden_states[layer][0][2], m2.hidden_states[layer][0][2])
output

tensor(0.6863, grad_fn=<SumBackward1>)

In [45]:
model

DistilBertForSequenceClassification(
  (distilbert): DistilBertModel(
    (embeddings): Embeddings(
      (word_embeddings): Embedding(30522, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (transformer): Transformer(
      (layer): ModuleList(
        (0-5): 6 x TransformerBlock(
          (attention): MultiHeadSelfAttention(
            (dropout): Dropout(p=0.1, inplace=False)
            (q_lin): Linear(in_features=768, out_features=768, bias=True)
            (k_lin): Linear(in_features=768, out_features=768, bias=True)
            (v_lin): Linear(in_features=768, out_features=768, bias=True)
            (out_lin): Linear(in_features=768, out_features=768, bias=True)
          )
          (sa_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
          (ffn): FFN(
            (dropout): Dropout(p=0.1, inplace=False)
 